package com.ihsinformatics.gfatmmobile.commonlab.persistance.entities;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.SqlUtils;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "attribute_type".
*/
public class AttributeTypeEntityDao extends AbstractDao<AttributeTypeEntity, Long> {

    public static final String TABLENAME = "attribute_type";

    /**
     * Properties of entity AttributeTypeEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Uuid = new Property(1, String.class, "uuid", false, "UUID");
        public final static Property Display = new Property(2, String.class, "display", false, "DISPLAY");
        public final static Property Name = new Property(3, String.class, "name", false, "NAME");
        public final static Property TestTypeId = new Property(4, Long.class, "testTypeId", false, "TEST_TYPE_ID");
        public final static Property DatatypeClassname = new Property(5, String.class, "datatypeClassname", false, "DATATYPE_CLASSNAME");
    }

    private DaoSession daoSession;


    public AttributeTypeEntityDao(DaoConfig config) {
        super(config);
    }
    
    public AttributeTypeEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"attribute_type\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"UUID\" TEXT UNIQUE ," + // 1: uuid
                "\"DISPLAY\" TEXT," + // 2: display
                "\"NAME\" TEXT," + // 3: name
                "\"TEST_TYPE_ID\" INTEGER NOT NULL ," + // 4: testTypeId
                "\"DATATYPE_CLASSNAME\" TEXT);"); // 5: datatypeClassname
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"attribute_type\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, AttributeTypeEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String uuid = entity.getUuid();
        if (uuid != null) {
            stmt.bindString(2, uuid);
        }
 
        String display = entity.getDisplay();
        if (display != null) {
            stmt.bindString(3, display);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(4, name);
        }
        stmt.bindLong(5, entity.getTestTypeId());
 
        String datatypeClassname = entity.getDatatypeClassname();
        if (datatypeClassname != null) {
            stmt.bindString(6, datatypeClassname);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, AttributeTypeEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String uuid = entity.getUuid();
        if (uuid != null) {
            stmt.bindString(2, uuid);
        }
 
        String display = entity.getDisplay();
        if (display != null) {
            stmt.bindString(3, display);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(4, name);
        }
        stmt.bindLong(5, entity.getTestTypeId());
 
        String datatypeClassname = entity.getDatatypeClassname();
        if (datatypeClassname != null) {
            stmt.bindString(6, datatypeClassname);
        }
    }

    @Override
    protected final void attachEntity(AttributeTypeEntity entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public AttributeTypeEntity readEntity(Cursor cursor, int offset) {
        AttributeTypeEntity entity = new AttributeTypeEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // uuid
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // display
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // name
            cursor.getLong(offset + 4), // testTypeId
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5) // datatypeClassname
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, AttributeTypeEntity entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUuid(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setDisplay(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setName(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setTestTypeId(cursor.getLong(offset + 4));
        entity.setDatatypeClassname(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(AttributeTypeEntity entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(AttributeTypeEntity entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(AttributeTypeEntity entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getTestTypeEntityDao().getAllColumns());
            builder.append(" FROM attribute_type T");
            builder.append(" LEFT JOIN test_type T0 ON T.\"TEST_TYPE_ID\"=T0.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected AttributeTypeEntity loadCurrentDeep(Cursor cursor, boolean lock) {
        AttributeTypeEntity entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        TestTypeEntity testType = loadCurrentOther(daoSession.getTestTypeEntityDao(), cursor, offset);
         if(testType != null) {
            entity.setTestType(testType);
        }

        return entity;    
    }

    public AttributeTypeEntity loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<AttributeTypeEntity> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<AttributeTypeEntity> list = new ArrayList<AttributeTypeEntity>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<AttributeTypeEntity> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<AttributeTypeEntity> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
