package com.ihsinformatics.gfatmmobile.commonlab.persistance.entities;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.ihsinformatics.gfatmmobile.commonlab.persistance.entities.AttributeEntity;
import com.ihsinformatics.gfatmmobile.commonlab.persistance.entities.AttributeTypeEntity;
import com.ihsinformatics.gfatmmobile.commonlab.persistance.entities.ConceptEntity;
import com.ihsinformatics.gfatmmobile.commonlab.persistance.entities.MedicationDoseUnit;
import com.ihsinformatics.gfatmmobile.commonlab.persistance.entities.MedicationDrug;
import com.ihsinformatics.gfatmmobile.commonlab.persistance.entities.MedicationDuration;
import com.ihsinformatics.gfatmmobile.commonlab.persistance.entities.MedicationFrequency;
import com.ihsinformatics.gfatmmobile.commonlab.persistance.entities.MedicationRoute;
import com.ihsinformatics.gfatmmobile.commonlab.persistance.entities.TestOrderEntity;
import com.ihsinformatics.gfatmmobile.commonlab.persistance.entities.TestTypeEntity;

import com.ihsinformatics.gfatmmobile.commonlab.persistance.entities.AttributeEntityDao;
import com.ihsinformatics.gfatmmobile.commonlab.persistance.entities.AttributeTypeEntityDao;
import com.ihsinformatics.gfatmmobile.commonlab.persistance.entities.ConceptEntityDao;
import com.ihsinformatics.gfatmmobile.commonlab.persistance.entities.MedicationDoseUnitDao;
import com.ihsinformatics.gfatmmobile.commonlab.persistance.entities.MedicationDrugDao;
import com.ihsinformatics.gfatmmobile.commonlab.persistance.entities.MedicationDurationDao;
import com.ihsinformatics.gfatmmobile.commonlab.persistance.entities.MedicationFrequencyDao;
import com.ihsinformatics.gfatmmobile.commonlab.persistance.entities.MedicationRouteDao;
import com.ihsinformatics.gfatmmobile.commonlab.persistance.entities.TestOrderEntityDao;
import com.ihsinformatics.gfatmmobile.commonlab.persistance.entities.TestTypeEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig attributeEntityDaoConfig;
    private final DaoConfig attributeTypeEntityDaoConfig;
    private final DaoConfig conceptEntityDaoConfig;
    private final DaoConfig medicationDoseUnitDaoConfig;
    private final DaoConfig medicationDrugDaoConfig;
    private final DaoConfig medicationDurationDaoConfig;
    private final DaoConfig medicationFrequencyDaoConfig;
    private final DaoConfig medicationRouteDaoConfig;
    private final DaoConfig testOrderEntityDaoConfig;
    private final DaoConfig testTypeEntityDaoConfig;

    private final AttributeEntityDao attributeEntityDao;
    private final AttributeTypeEntityDao attributeTypeEntityDao;
    private final ConceptEntityDao conceptEntityDao;
    private final MedicationDoseUnitDao medicationDoseUnitDao;
    private final MedicationDrugDao medicationDrugDao;
    private final MedicationDurationDao medicationDurationDao;
    private final MedicationFrequencyDao medicationFrequencyDao;
    private final MedicationRouteDao medicationRouteDao;
    private final TestOrderEntityDao testOrderEntityDao;
    private final TestTypeEntityDao testTypeEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        attributeEntityDaoConfig = daoConfigMap.get(AttributeEntityDao.class).clone();
        attributeEntityDaoConfig.initIdentityScope(type);

        attributeTypeEntityDaoConfig = daoConfigMap.get(AttributeTypeEntityDao.class).clone();
        attributeTypeEntityDaoConfig.initIdentityScope(type);

        conceptEntityDaoConfig = daoConfigMap.get(ConceptEntityDao.class).clone();
        conceptEntityDaoConfig.initIdentityScope(type);

        medicationDoseUnitDaoConfig = daoConfigMap.get(MedicationDoseUnitDao.class).clone();
        medicationDoseUnitDaoConfig.initIdentityScope(type);

        medicationDrugDaoConfig = daoConfigMap.get(MedicationDrugDao.class).clone();
        medicationDrugDaoConfig.initIdentityScope(type);

        medicationDurationDaoConfig = daoConfigMap.get(MedicationDurationDao.class).clone();
        medicationDurationDaoConfig.initIdentityScope(type);

        medicationFrequencyDaoConfig = daoConfigMap.get(MedicationFrequencyDao.class).clone();
        medicationFrequencyDaoConfig.initIdentityScope(type);

        medicationRouteDaoConfig = daoConfigMap.get(MedicationRouteDao.class).clone();
        medicationRouteDaoConfig.initIdentityScope(type);

        testOrderEntityDaoConfig = daoConfigMap.get(TestOrderEntityDao.class).clone();
        testOrderEntityDaoConfig.initIdentityScope(type);

        testTypeEntityDaoConfig = daoConfigMap.get(TestTypeEntityDao.class).clone();
        testTypeEntityDaoConfig.initIdentityScope(type);

        attributeEntityDao = new AttributeEntityDao(attributeEntityDaoConfig, this);
        attributeTypeEntityDao = new AttributeTypeEntityDao(attributeTypeEntityDaoConfig, this);
        conceptEntityDao = new ConceptEntityDao(conceptEntityDaoConfig, this);
        medicationDoseUnitDao = new MedicationDoseUnitDao(medicationDoseUnitDaoConfig, this);
        medicationDrugDao = new MedicationDrugDao(medicationDrugDaoConfig, this);
        medicationDurationDao = new MedicationDurationDao(medicationDurationDaoConfig, this);
        medicationFrequencyDao = new MedicationFrequencyDao(medicationFrequencyDaoConfig, this);
        medicationRouteDao = new MedicationRouteDao(medicationRouteDaoConfig, this);
        testOrderEntityDao = new TestOrderEntityDao(testOrderEntityDaoConfig, this);
        testTypeEntityDao = new TestTypeEntityDao(testTypeEntityDaoConfig, this);

        registerDao(AttributeEntity.class, attributeEntityDao);
        registerDao(AttributeTypeEntity.class, attributeTypeEntityDao);
        registerDao(ConceptEntity.class, conceptEntityDao);
        registerDao(MedicationDoseUnit.class, medicationDoseUnitDao);
        registerDao(MedicationDrug.class, medicationDrugDao);
        registerDao(MedicationDuration.class, medicationDurationDao);
        registerDao(MedicationFrequency.class, medicationFrequencyDao);
        registerDao(MedicationRoute.class, medicationRouteDao);
        registerDao(TestOrderEntity.class, testOrderEntityDao);
        registerDao(TestTypeEntity.class, testTypeEntityDao);
    }
    
    public void clear() {
        attributeEntityDaoConfig.clearIdentityScope();
        attributeTypeEntityDaoConfig.clearIdentityScope();
        conceptEntityDaoConfig.clearIdentityScope();
        medicationDoseUnitDaoConfig.clearIdentityScope();
        medicationDrugDaoConfig.clearIdentityScope();
        medicationDurationDaoConfig.clearIdentityScope();
        medicationFrequencyDaoConfig.clearIdentityScope();
        medicationRouteDaoConfig.clearIdentityScope();
        testOrderEntityDaoConfig.clearIdentityScope();
        testTypeEntityDaoConfig.clearIdentityScope();
    }

    public AttributeEntityDao getAttributeEntityDao() {
        return attributeEntityDao;
    }

    public AttributeTypeEntityDao getAttributeTypeEntityDao() {
        return attributeTypeEntityDao;
    }

    public ConceptEntityDao getConceptEntityDao() {
        return conceptEntityDao;
    }

    public MedicationDoseUnitDao getMedicationDoseUnitDao() {
        return medicationDoseUnitDao;
    }

    public MedicationDrugDao getMedicationDrugDao() {
        return medicationDrugDao;
    }

    public MedicationDurationDao getMedicationDurationDao() {
        return medicationDurationDao;
    }

    public MedicationFrequencyDao getMedicationFrequencyDao() {
        return medicationFrequencyDao;
    }

    public MedicationRouteDao getMedicationRouteDao() {
        return medicationRouteDao;
    }

    public TestOrderEntityDao getTestOrderEntityDao() {
        return testOrderEntityDao;
    }

    public TestTypeEntityDao getTestTypeEntityDao() {
        return testTypeEntityDao;
    }

}
