package com.ihsinformatics.gfatmmobile.commonlab.persistance.entities;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.ihsinformatics.gfatmmobile.commonlab.persistance.entities.AttributeTypeEntity;
import com.ihsinformatics.gfatmmobile.commonlab.persistance.entities.TestTypeEntity;

import com.ihsinformatics.gfatmmobile.commonlab.persistance.entities.AttributeTypeEntityDao;
import com.ihsinformatics.gfatmmobile.commonlab.persistance.entities.TestTypeEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig attributeTypeEntityDaoConfig;
    private final DaoConfig testTypeEntityDaoConfig;

    private final AttributeTypeEntityDao attributeTypeEntityDao;
    private final TestTypeEntityDao testTypeEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        attributeTypeEntityDaoConfig = daoConfigMap.get(AttributeTypeEntityDao.class).clone();
        attributeTypeEntityDaoConfig.initIdentityScope(type);

        testTypeEntityDaoConfig = daoConfigMap.get(TestTypeEntityDao.class).clone();
        testTypeEntityDaoConfig.initIdentityScope(type);

        attributeTypeEntityDao = new AttributeTypeEntityDao(attributeTypeEntityDaoConfig, this);
        testTypeEntityDao = new TestTypeEntityDao(testTypeEntityDaoConfig, this);

        registerDao(AttributeTypeEntity.class, attributeTypeEntityDao);
        registerDao(TestTypeEntity.class, testTypeEntityDao);
    }
    
    public void clear() {
        attributeTypeEntityDaoConfig.clearIdentityScope();
        testTypeEntityDaoConfig.clearIdentityScope();
    }

    public AttributeTypeEntityDao getAttributeTypeEntityDao() {
        return attributeTypeEntityDao;
    }

    public TestTypeEntityDao getTestTypeEntityDao() {
        return testTypeEntityDao;
    }

}
