package com.ihsinformatics.gfatmmobile.commonlab.persistance.entities;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "test_type".
*/
public class TestTypeEntityDao extends AbstractDao<TestTypeEntity, Long> {

    public static final String TABLENAME = "test_type";

    /**
     * Properties of entity TestTypeEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Uuid = new Property(1, String.class, "uuid", false, "UUID");
        public final static Property Display = new Property(2, String.class, "display", false, "DISPLAY");
        public final static Property TestGroup = new Property(3, String.class, "testGroup", false, "TEST_GROUP");
        public final static Property ShortName = new Property(4, String.class, "shortName", false, "SHORT_NAME");
        public final static Property RequiresSpecimen = new Property(5, Boolean.class, "requiresSpecimen", false, "REQUIRES_SPECIMEN");
        public final static Property Name = new Property(6, String.class, "name", false, "NAME");
        public final static Property Description = new Property(7, String.class, "description", false, "DESCRIPTION");
    }


    public TestTypeEntityDao(DaoConfig config) {
        super(config);
    }
    
    public TestTypeEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"test_type\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"UUID\" TEXT UNIQUE ," + // 1: uuid
                "\"DISPLAY\" TEXT," + // 2: display
                "\"TEST_GROUP\" TEXT," + // 3: testGroup
                "\"SHORT_NAME\" TEXT," + // 4: shortName
                "\"REQUIRES_SPECIMEN\" INTEGER," + // 5: requiresSpecimen
                "\"NAME\" TEXT," + // 6: name
                "\"DESCRIPTION\" TEXT);"); // 7: description
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"test_type\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, TestTypeEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String uuid = entity.getUuid();
        if (uuid != null) {
            stmt.bindString(2, uuid);
        }
 
        String display = entity.getDisplay();
        if (display != null) {
            stmt.bindString(3, display);
        }
 
        String testGroup = entity.getTestGroup();
        if (testGroup != null) {
            stmt.bindString(4, testGroup);
        }
 
        String shortName = entity.getShortName();
        if (shortName != null) {
            stmt.bindString(5, shortName);
        }
 
        Boolean requiresSpecimen = entity.getRequiresSpecimen();
        if (requiresSpecimen != null) {
            stmt.bindLong(6, requiresSpecimen ? 1L: 0L);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(7, name);
        }
 
        String description = entity.getDescription();
        if (description != null) {
            stmt.bindString(8, description);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, TestTypeEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String uuid = entity.getUuid();
        if (uuid != null) {
            stmt.bindString(2, uuid);
        }
 
        String display = entity.getDisplay();
        if (display != null) {
            stmt.bindString(3, display);
        }
 
        String testGroup = entity.getTestGroup();
        if (testGroup != null) {
            stmt.bindString(4, testGroup);
        }
 
        String shortName = entity.getShortName();
        if (shortName != null) {
            stmt.bindString(5, shortName);
        }
 
        Boolean requiresSpecimen = entity.getRequiresSpecimen();
        if (requiresSpecimen != null) {
            stmt.bindLong(6, requiresSpecimen ? 1L: 0L);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(7, name);
        }
 
        String description = entity.getDescription();
        if (description != null) {
            stmt.bindString(8, description);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public TestTypeEntity readEntity(Cursor cursor, int offset) {
        TestTypeEntity entity = new TestTypeEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // uuid
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // display
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // testGroup
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // shortName
            cursor.isNull(offset + 5) ? null : cursor.getShort(offset + 5) != 0, // requiresSpecimen
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // name
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7) // description
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, TestTypeEntity entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUuid(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setDisplay(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setTestGroup(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setShortName(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setRequiresSpecimen(cursor.isNull(offset + 5) ? null : cursor.getShort(offset + 5) != 0);
        entity.setName(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setDescription(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(TestTypeEntity entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(TestTypeEntity entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(TestTypeEntity entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
